version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - unzip terraform.zip
      - sudo mv terraform /usr/local/bin/
      - rm terraform.zip
      - terraform --version
  pre_build:
    commands:
      - echo "Running terraform init..."
      - terraform init
  build:
    commands:
      - echo "Running terraform plan..."
      - terraform plan
      - echo "Running terraform apply..."
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'

    