apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-job
spec:
  template:
    spec:
      containers:
      - name: pytorch-container
        image: 499969923602.dkr.ecr.ap-southeast-1.amazonaws.com/issdsai-k8s-job:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never

